site_name: Infographic Challenge

theme:
  name: null
  custom_dir: 'cinder'

site_dir: '../docs'

nav:
  - Home: 'index.md'
#  - Learning Resources: 'resources.md'

extra:
  logo: 'assets/images/esri_globe.png'
